[package]
name = "python-ir"
version = "0.1.0"
authors = ["Peter Delevoryas <peter.delevoryas@colorado.edu>"]

[dependencies]
lazy_static = "0.2"
regex = "0.2"
python-ast = { path = "../ast" }

[dev-dependencies]
python-token = { path = "../token" }
